# Generated by Django 4.2.4 on 2023-08-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_nicknames"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="leader",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
            ),
        ),
    ]
