# Generated by Django 4.2.4 on 2023-08-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_nicknames"),
        ("nicknames", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nickname",
            name="team",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
            preserve_default=False,
        ),
    ]
