# Generated by Django 4.2.4 on 2023-08-11 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nicknames", "0003_nickname_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nickname",
            name="description",
        ),
    ]
