# Generated by Django 4.2.4 on 2023-08-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_nicknames"),
        ("schedules", "0004_alter_schedule_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
    ]
