# Generated by Django 4.2.4 on 2023-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamname", models.CharField(max_length=20)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#F44336", "Red"),
                            ("#E91E63", "Pink"),
                            ("#9C27B0", "Purple"),
                            ("#673AB7", "Deep Purple"),
                            ("#3F51B5", "Indigo"),
                            ("#2196F3", "Blue"),
                            ("#03A9F4", "Light Blue"),
                            ("#00BCD4", "Cyan"),
                            ("#009688", "Teal"),
                            ("#4CAF50", "Green"),
                            ("#8BC34A", "Light Green"),
                            ("#CDDC39", "Lime"),
                            ("#FFEB3B", "Yellow"),
                            ("#FFC107", "Amber"),
                            ("#FF9800", "Orange"),
                            ("#FF5722", "Deep Orange"),
                        ],
                        default="#9C27B0",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
