# Generated by Django 4.2.4 on 2023-08-10 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="nicknames",
        ),
    ]
